
CREATE  FUNCTION dbo.fn__GetPrimaryKey (
	@table 		VARCHAR(100) 
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @pkid_field VARCHAR(100)
	SELECT 	@pkid_field = ''
	SELECT 	@pkid_field = COLUMN_NAME
		
	FROM 	INFORMATION_SCHEMA.TABLE_CONSTRAINTS c, 
		INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE u
	WHERE	c.CONSTRAINT_NAME = u.CONSTRAINT_NAME 
	AND	c.CONSTRAINT_TYPE = 'PRIMARY KEY'
	AND 	c.TABLE_NAME = @table
	RETURN @pkid_field
END